
language: android

jdk:
  - oraclejdk8

notifications:
  email:
    - justcoxier@gmail.com
    - aliezted@gmail.com
env:
  matrix:
    - TEST=unit
    - TEST=android ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a ADB_INSTALL_TIMEOUT=10
  global:
    - ADB_INSTALL_TIMEOUT=10
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"


sudo: required

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-23
    - android-24
    - android-25
    - extra-android-support
    - extra-android-m2repository
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-25


licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
    - sudo apt-get update


addons:
  apt_packages:
    - pandoc

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/


before_script:
  - android list targets
  - ./gradlew clean
  - ./create_avd.sh


cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
     - ./building.sh
     - ./run_tests.sh

after_script:
    - "pandoc $TRAVIS_BUILD_DIR/parsingplayer/build/reports/androidTests/connected/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'"
    - cat logcat.log; pkill -KILL -f adb
after_failure:
    - "pandoc $TRAVIS_BUILD_DIR/parsingplayer/build/reports/androidTests/connected/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'"
    - cat logcat.log; pkill -KILL -f adb